version: 2
project_name: egresszero

builds:
  - main: ./cmd/egresszero
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/muhammetsafak/egresszero/internal/version.version=v{{ .Version }}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  use: github-native

release:
  footer: |
    ## Docker

    ```sh
    docker pull ghcr.io/muhammetsafak/egresszero:{{ .Version }}
    ```
